### ISSUE TITLE
Use chef-sugar for compile

### ISSUE THREAD

**Issue by AMeng** [chef-cookbooks/xml#15]
As mentioned in https://github.com/opscode-cookbooks/xml/pull/11 `chef-sugar` should be used for compile-time actions:

I think it would be preferable to use the chef-sugar cookbook's compile_time method to do this instead.
```
compile_time do
  package pkg
end
```
This would be in the default recipe. In the ruby recipe, we'd want to use compile_time with the apt-get update execute resource.

**Comment by tas50** [comment]
I've actually removed chef-sugar usage since we get compile time without the additional dep
