### ISSUE TITLE
README is incorrect about use_system_libraries

### ISSUE THREAD

**Issue by nicwaller** [chef-cookbooks/xml#20]
Starting with ef4f828 in July 2014, the default for `use_system_libraries` changed to `false`. However, the [README](https://github.com/opscode-cookbooks/xml/blob/106ff70638b2081c876aa3b167f386996e17110b/README.md#attributes) still indicates that it defaults to `true`.

**Comment by tas50** [comment]
I've updated the readme.  Thanks
