### ISSUE TITLE
If platform is unsupported, don't try to install empty array of packages

### ISSUE THREAD

**Issue by martinb3** [chef-cookbooks/xml#33]
### Cookbook version
master

### Chef-client version
12.16.42

### Platform Details
Windows server 2012 R2

### Scenario:

If `node['platform_family']` isn't one of the supported values, `default['xml']['packages'] = []` and users get a misleading error:
```
NoMethodError: undefined method `downcase' for []:Chef::Node::ImmutableArray
```

### Steps to Reproduce:

I've got a user who reproduced it by running `xml::default` on Windows-based platform: https://github.com/martinb3-cookbooks/xmledit-cookbook/issues/19

### Expected result

Perhaps this cookbook should blow up with a better message or skip installing packages if the array is empty (maybe something like `only_if { node['xml']['packages'].length == 0 }`?).

**Comment by tas50** [comment]
I ran into this with ark as well. We'll have to be more defensive in the future.

**Comment by tas50** [comment]
Give 3.1.0 a try and let me know if that works better for you. I added a pile of specs to avoid this in the future.

**Comment by martinb3** [comment]
Thanks @tas50!
