### ISSUE TITLE
node.set is deprecated

### ISSUE THREAD

**Issue by soren121** [chef-cookbooks/xml#35]
### Cookbook version
3.1.0

### Chef-client version
12.16.42

### Platform Details
Amazon OpsWorks (Chef 12, Linux)

### Scenario:
During deployments, I get a deprecation warning in my log for the xml cookbook:

> WARN: node.set is deprecated and will be removed in Chef 14, please use node.default/node.override (or node.normal only if you really need persistence)

The warning is for _attributes/ruby.rb_, line 1:
```
set['build-essential']['compile_time'] = true
```

Presumably, `set` should be changed to `normal`, but I'm not a very experienced Chef user so I'm not sure.

**Comment by kamaradclimber** [comment]
Since xml depends on build-essential, there is no reason to set the `normal` priority (with `normal['build-essential']['compile_time']` or via `node.set[...]`).

Simply using:
```
default['build-essential']['compile_time'] = true
```

will:
- fix the issue
- keep the same behavior
